/** Declaration file generated by dts-gen */

export const MAX_CODEPOINT: number

export function UTF16toUTF8(src: any, dst: any): void

export function UTF8toUTF16(src: any, dst: any): any

export function arrayDestination(a: any): any

export function arraySource(a: any): any

export function assertCharCode(c: any): any

export function assertCodePoint(cp: any): any

export function calculateCodePoint(cp: any): any

export function calculateUTF16asUTF8(src: any): any

export function calculateUTF8(src: any): any

export function codePointAt(s: any, i: any): any

export function decodeUTF8(src: any, dst: any): void

export function decodeUTF8toUTF16(src: any, dst: any): void

export function encodeUTF16toUTF8(src: any, dst: any): void

export function encodeUTF8(src: any, dst: any): any

export function fromCodePoint(var_args: any, ...args: any[]): any

export function polyfill(override: any): any

export function stringDestination(...args: any[]): any

export function stringSource(s: any): any
